services:
  - type: web
    name: api-school
    runtime: node
    plan: free
    healthCheckPath: /health
    buildCommand: bash render-build.sh
    startCommand: cd backend-csp && node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
